experiment: apmgsrn_combustion_40NH3_1_Mole_Fraction_of_CH4
exp_id: apmgsrn-combustion_40NH3_1-Mole_Fraction_of_CH4
experiment_root: ${REPO_ROOT}/runs
MODEL:
  model_name: apmgsrn
  n_dims: 3
  n_outputs: 1
  feature_grid_shape:
  - 4
  - 4
  - 4
  n_features: 14
  n_grids: 1
  nodes_per_layer: 16
  n_layers: 3
  use_bias: false
  use_tcnn_if_available: true
  grid_initialization: default
  requires_padded_feats: true
DATA:
  dataset_name: combustion_40NH3_1
  target: Mole_Fraction_of_CH4
  targets:
    Absolute_Pressure: ${COMBUSTION_ROOT}/target_Absolute_Pressure.npy
    Chemistry_Heat_Release_Rate: ${COMBUSTION_ROOT}/target_Chemistry_Heat_Release_Rate.npy
    Mole_Fraction_of_CH4: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_CH4.npy
    Mole_Fraction_of_CO: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_CO.npy
    Mole_Fraction_of_CO2: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_CO2.npy
    Mole_Fraction_of_H2O: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_H2O.npy
    Mole_Fraction_of_NH2: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_NH2.npy
    Mole_Fraction_of_NH3: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_NH3.npy
    Mole_Fraction_of_OH: ${COMBUSTION_ROOT}/target_Mole_Fraction_of_OH.npy
    Pressure: ${COMBUSTION_ROOT}/target_Pressure.npy
    Temperature: ${COMBUSTION_ROOT}/target_Temperature.npy
    Velocity_Magnitude: ${COMBUSTION_ROOT}/target_Velocity_Magnitude.npy
  volume_shape:
    X: 128
    Y: 128
    Z: 1
    T: 2001
  align_corners: true
TRAINING:
  iterations: 450
  points_per_iteration: 16000
  prediction_points_per_batch: 16000
  lr: 0.01
  beta_1: 0.9
  beta_2: 0.99
  device: cuda:0
  data_device: same
  save_every: 0
  log_every: 100
  time_indices: all
  seed: 42
  early_stopping: false
EVALUATION:
  run_after_training: false
