seed: 0
wandb_project: inr_moe_ionization
experiment: neural_expert_ionization-size326_H2-managerpretrain
exp_id: neural-expert-ionization-size326-H2-managerpretrain
experiment_root: ${REPO_ROOT}/runs/neural_expert
MODEL:
  model_name: inr_moe_ionization
  in_dim: 4
  out_dim: 1
  decoder_hidden_dim: 33
  decoder_n_hidden_layers: 2
  decoder_input_encoding: learned_264_2_sine_siren_none
  decoder_nl: sine
  decoder_init_type: siren
  n_experts: 8
  outermost_linear: true
  input_encoding: none
  decoder_freqs: 30.0
  decoder_trainable_freqs: false
  top_k: 1
  manager_hidden_dim: 66
  manager_n_hidden_layers: 2
  manager_input_encoding: learned_66_2_sine_siren_none
  manager_nl: sine
  manager_init: siren
  manager_type: standard
  experts_bias_std: 0.1
  experts_bias_weight: 1.0
  manager_softmax_temperature: 1.0
  manager_softmax_temp_trainable: false
  manager_q_activation: softmax
  manager_clamp_q: 0.0
  manager_conditioning: cat
  manager_pt_path: ${REPO_ROOT}/runs/neural_expert/pretrained_managers/ionization/size326/pt_inr_moe_ionization_H2_managerpretraining.pth
  load_pt_manager: false
  shared_encoder: false
LOSS:
  scale_by_q_grad: false
  loss_type: 1000segmentation
  segmentation_type: both
  sample_bias_correction: false
  entropy_metric: kl
DATA:
  dataset_name: ionization
  target: H2
  targets:
    GT: ${REPO_ROOT}/data/Volume/Ionization/target_GT.npy
    H_plus: ${REPO_ROOT}/data/Volume/Ionization/target_H+.npy
    H2: ${REPO_ROOT}/data/Volume/Ionization/target_H2.npy
    He: ${REPO_ROOT}/data/Volume/Ionization/target_He.npy
    PD: ${REPO_ROOT}/data/Volume/Ionization/target_PD.npy
  target_stats_path: ${REPO_ROOT}/data/cache/neural_expert/ionization/target_stats_H2.npz
  normalize_inputs: true
  normalize_targets: false
  volume_shape:
    X: 600
    Y: 248
    Z: 248
    T: 100
  segmentation_type: random_balanced
  grid_patch_size: 4
  n_segments: 8
TRAINING:
  n_points: 16000
  lr: 3.0e-05
  lr_gamma: 0.9999
  lr_scheduler: ExponentialLR
  num_epochs: 30000
  batch_size: 1
  num_workers: 0
  grad_clip_norm: 10.0
  save_every: 500
  segmentation_mode: true
  log_every: 100
  stages:
  - end_iteration_frac: 1.0
    params: all
    loss_type: 1000segmentation
