experiment: apmgsrn_ionization_{target}
exp_id: apmgsrn-ionization-{target}
experiment_root: ../../runs/apmgsrn
MODEL:
  model_name: apmgsrn
  n_dims: 3
  n_outputs: 1
  feature_grid_shape: [8, 8, 8]
  n_features: 2
  n_grids: 64
  nodes_per_layer: 64
  n_layers: 2
  use_bias: false
  use_tcnn_if_available: true
  grid_initialization: default
DATA:
  dataset_name: ionization
  target: GT
  targets:
    GT: ../../data/Volume/Ionization/target_GT.npy
    H_plus: ../../data/Volume/Ionization/target_H+.npy
    H2: ../../data/Volume/Ionization/target_H2.npy
    He: ../../data/Volume/Ionization/target_He.npy
    PD: ../../data/Volume/Ionization/target_PD.npy
  volume_shape:
    X: 600
    Y: 248
    Z: 248
    T: 100
  align_corners: true
TRAINING:
  iterations: 10000
  points_per_iteration: 100000
  prediction_points_per_batch: 100000
  lr: 0.01
  beta_1: 0.9
  beta_2: 0.99
  device: cuda:0
  data_device: same
  save_every: 0
  log_every: 100
  time_indices: all
  seed: 42
