experiment: mesh_car_var_expert
exp_id: var-expert-car
experiment_root: runs
data:
  kind: node
  dataset_name: car
  split: train
  coords_path: ../../data/Mesh/Car/source_XYZT.npy
  targets:
    CoefPressure: ../../data/Mesh/Car/target_CoefPressure.npy
    dp-dX: ../../data/Mesh/Car/target_dp-dX.npy
    dp-dY: ../../data/Mesh/Car/target_dp-dY.npy
    dp-dZ: ../../data/Mesh/Car/target_dp-dZ.npy
    EnergyInternal: ../../data/Mesh/Car/target_EnergyInternal.npy
    Enthalpy: ../../data/Mesh/Car/target_Enthalpy.npy
    EnthalpyStagnation: ../../data/Mesh/Car/target_EnthalpyStagnation.npy
    Lambda_2_Criterion: ../../data/Mesh/Car/target_Lambda_2_Criterion.npy
    Pressure: ../../data/Mesh/Car/target_Pressure.npy
    PressureDynamic: ../../data/Mesh/Car/target_PressureDynamic.npy
    Production_of_k: ../../data/Mesh/Car/target_Production_of_k.npy
    Q_Criterion_Raw: ../../data/Mesh/Car/target_Q_Criterion_Raw.npy
    Skin_Friction_Coefficient: ../../data/Mesh/Car/target_Skin_Friction_Coefficient.npy
    SkinFrictionMagnitude: ../../data/Mesh/Car/target_SkinFrictionMagnitude.npy
    SkinFrictionX: ../../data/Mesh/Car/target_SkinFrictionX.npy
    SkinFrictionY: ../../data/Mesh/Car/target_SkinFrictionY.npy
    SkinFrictionZ: ../../data/Mesh/Car/target_SkinFrictionZ.npy
    Strain_Rate: ../../data/Mesh/Car/target_Strain_Rate.npy
    Turbulent_Intensity: ../../data/Mesh/Car/target_Turbulent_Intensity.npy
    Turbulent_Viscosity_Ratio: ../../data/Mesh/Car/target_Turbulent_Viscosity_Ratio.npy
    TurbulentDissipation: ../../data/Mesh/Car/target_TurbulentDissipation.npy
    TurbulentEnergyKinetic: ../../data/Mesh/Car/target_TurbulentEnergyKinetic.npy
    ViscosityEddy: ../../data/Mesh/Car/target_ViscosityEddy.npy
    VorticityMagnitude: ../../data/Mesh/Car/target_VorticityMagnitude.npy
    VorticityX: ../../data/Mesh/Car/target_VorticityX.npy
    VorticityY: ../../data/Mesh/Car/target_VorticityY.npy
    VorticityZ: ../../data/Mesh/Car/target_VorticityZ.npy
    Wall_Yplus: ../../data/Mesh/Car/target_Wall_Yplus.npy
model:
  name: var_expert
  in_features: 4
  num_experts: 6
  base_dim: 8
  top_k: 3
training:
  epochs: 600
  batch_size: 16000
  pred_batch_size: 16000
  num_workers: 0
  lr: 5.0e-5
  val_split: 0.0
  log_every: 10
  log_psnr_every: 10
  psnr_sample_ratio: 0.1
  save_every: 600
  early_stop_patience: 0
  loss_type: mse
  seed: 42
  sampler: budgeted_random
  batches_per_epoch_budget: 1500
  multiview_ema_loss:
    enabled: true
    beta: 0.95
    eps: 1.0e-8
    w_min: 0.2
    w_max: 5.0
    warmup_steps: 45000
  scheduler:
    enabled: true
    step_size: 40
    gamma: 0.92
  pretrain:
    enabled: false
    epochs: 0
evaluation:
  batch_size: 16000
  save_predictions: true

